# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' R's implementation of the Moore-Penrose pseudo matrix inverse
#'
#' @param m matrix
Rginv <- function(m) {
    .Call(`_kalmanfilter_Rginv`, m)
}

#' Generalized matrix inverse
#'
#' @param m matrix
gen_inv <- function(m) {
    .Call(`_kalmanfilter_gen_inv`, m)
}

#' Kalman Likelihood
#'
#' @param sp list describing the state space model
#' @param yt matrix of data
#' @param Xo matrix of exogenous observation data
#' @param Xs matrix of exogenous state data
#' @param w matrix of weights
likelihood <- function(sp, yt, Xo, Xs, w) {
    .Call(`_kalmanfilter_likelihood`, sp, yt, Xo, Xs, w)
}

#' Kalman Filter
#'
#' @param sp list describing the state space model
#' @param yt matrix of data
#' @param Xo matrix of exogenous observation data
#' @param Xs matrix of exogenous state data
#' @param smooth boolean indication whether to run the backwards smoother
filter <- function(sp, yt, Xo, Xs, smooth = FALSE) {
    .Call(`_kalmanfilter_filter`, sp, yt, Xo, Xs, smooth)
}

