# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Rginv <- function(m) {
    .Call(`_kalmanfilter_Rginv`, m)
}

gen_inv <- function(m) {
    .Call(`_kalmanfilter_gen_inv`, m)
}

contains <- function(s, L) {
    .Call(`_kalmanfilter_contains`, s, L)
}

kalman_filter_cpp <- function(ssm, yt, Xo = NULL, Xs = NULL, weight = NULL, smooth = FALSE) {
    .Call(`_kalmanfilter_kalman_filter_cpp`, ssm, yt, Xo, Xs, weight, smooth)
}

kalman_filter_tvp_cpp <- function(ssm, yt, Xo = NULL, Xs = NULL, weight = NULL, smooth = FALSE) {
    .Call(`_kalmanfilter_kalman_filter_tvp_cpp`, ssm, yt, Xo, Xs, weight, smooth)
}

